name: Benchmark and Update Badges
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: benchmark
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Yandex Container Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: oauth
          password: ${{ secrets.YANDEX_OAUTH_TOKEN }}

      - name: Build and Push Image
        run: |
          docker build -t cr.yandex/crpd6c2nbgpc62degbju/tech-practice:latest .

          docker push cr.yandex/crpd6c2nbgpc62degbju/tech-practice:latest
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Benchmarks
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python scripts/benchmark.py
      - name: Deploy Badges to Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./badges
          publish_branch: badges